### PR TITLE
Table of Elements, and "generators" directory

### PR DESCRIPTION
**Pull request by dtgriscom**
This includes two items which may be considered separately:

1.  A new "Table of Elements" cheatsheet, which gives the atomic number, symbol, name, atomic mass, default state, default density, and year of discovery for each element (a link to the Wikipedia page is also included)

2. The code used to generate the above cheatsheet, in a new "generators" directory. (I also added a note about the "generators" directory to the ReadMe.md.)

### CODE REVIEW

**Comment by dtgriscom** [comment]
Not being much of a Ruby person, my generator script just writes to stdout, and must be piped in the shell. I'd be happy to have it write directly to the cheat sheet file, but a pointer as to how would be welcome.

**Comment by dtgriscom** [comment]
Please hang fire on this; I'm investigating a better data source.

**Comment by Kapeli** [comment]
1. That's fine, but please rename it to "Periodic Table" or "Periodic Table of Elements".

2. There are some generators already in the [resources](https://github.com/Kapeli/cheatsheets/tree/master/resources) folder. Add your generator to `resources` instead. Don't make a note in the README about it, as I don't want to encourage this practice (generators often stop working, making cheat sheets hard to update).

> Not being much of a Ruby person, my generator script just writes to stdout, and must be piped in the shell. I'd be happy to have it write directly to the cheat sheet file, but a pointer as to how would be welcome.

I don't know much Ruby either. I'd start with https://stackoverflow.com/questions/2777802/how-to-write-to-file-in-ruby.

**Comment by dtgriscom** [comment]
1: I'd named it "Table of Elements", because it clearly is not the **Periodic** Table of Elements; it has no information as to the [periodic arrangement](https://en.wikipedia.org/wiki/Periodic_table#Overview) [Mendeleev](https://en.wikipedia.org/wiki/Dmitri_Mendeleev) came up with. If you need me to rename it, though, I'll do so. If you think it would be possible to have that wide a table in a cheatsheet (18 rows!) then I'd consider rebuilding things around that.

2. I hadn't looked inside the "resources" folder; I'll move my generation code there. I'll also remove the change to the ReadMe file.

I don't share your concern about using generator code, though. Sure, the source could disappear or its format could change, breaking the generation. However, even if it does break you'll still have the previously-generated cheatsheet, and in any case a cheatsheet that's made by hand is still far more likely to become outdated.

So, should I leave the name as-is, or rename it to Periodic Table of Elements? (I'm not likely to have time to make it an actual Periodic table in the near future.)

**Comment by Kapeli** [comment]
> So, should I leave the name as-is, or rename it to Periodic Table of Elements? (I'm not likely to have time to make it an actual Periodic table in the near future.)

Ah, I see. My issue is really that Dash is a programmer tool. While I'm ok with having cheat sheets that aren't programming-related, I also would like for them to be somewhat obvious that they aren't programming related. Maybe "Table of Chemical Elements" is ok? Or just "Chemical Elements"?

It's ok to leave it as "Table of Elements" as well. I'll have to add a way in Dash to differentiate between programming cheat sheets and the rest anyway.

**Comment by dtgriscom** [comment]
Oh, and the numeric index entries are sorted alphabetical, rather than numerical or in the order added. (I hope I'm not being too much of a PIA about all this non-coding stuff; I'm just having fun with it.)

**Comment by Kapeli** [comment]
I've added support for multiple index entries.

Update to the latest cheatset (1.3.8) and then use this:

```
entry do
  td_notes '2'
  td_notes 'He'
  td_notes '[helium](https://en.wikipedia.org/wiki/Helium)'
  td_notes '4.002602(2)'
  td_notes 'gas'
  td_notes '0.0001785'
  td_notes '1868'
  index_name 'helium'
  extra_index_name '2'
end
```

You can use as many `extra_index_name` as you want. The difference between `index_name` and `extra_index_name` is that `index_name` appears in the list at the bottom left while `extra_index_name` doesn't.

> Oh, and the numeric index entries are sorted alphabetical, rather than numerical or in the order added. (I hope I'm not being too much of a PIA about all this non-coding stuff; I'm just having fun with it.)

I'll try to fix this within Dash.

**Comment by dtgriscom** [comment]
Done, and thanks.

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by Kapeli** [comment]
Note: I've removed some of the styling (https://github.com/Kapeli/cheatsheets/commit/2fb7f3d745ccd55af8375758b826cdee5c3ff8fe), to keep the cheat sheet looking like the other ones.

**Comment by dtgriscom** [comment]
Works for me: thanks.

**Pull request merged**
