### PR TITLE
Adding Trello Cheat sheet

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
This is my first attempt at creating a cheatsheet and I have many others I want to submit, so please let me know if anything needs changing :)

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
@Kapeli No reason! As I say, this is my first PR to Dash, so don't assume any mistake is intentional :)

**Comment by ChrisChinchilla** [comment]
Updated

**Comment by ChrisChinchilla** [comment]
@Kapeli OK! I saw 'or' used in other cheatsheets, but will change.

**Comment by Kapeli** [comment]
> @Kapeli No reason! As I say, this is my first PR to Dash, so don't assume any mistake is intentional :)

I wasn't sure it's a mistake really so I asked if there's a reason. No worries :+1: 

> @Kapeli OK! I saw 'or' used in other cheatsheets, but will change, and lowercase was what Trello used in their own guides, but again, sure, will change.

Where did you see `or` in other cheat sheets? They need to be fixed.

> Might be good to mention some of these things in the submission guide.

Nope. I want to keep the guidelines simple to reduce the barrier for contributions. Usually I just accept the cheat sheet and make the changes myself to make it consistent with the others, but you said you have many others to submit so I thought it might be better to be thorough in this case.

**Comment by Kapeli** [comment]
Also: what do you think about naming the cheat sheet just Trello and having Keyboard Shortcuts as the category?

**Comment by ChrisChinchilla** [comment]
@Kapeli I saw an 'Or' in the Mac Startup keys cheat sheet. Happy to change title and categories. Hopefully all done now.

**Comment by Kapeli** [comment]
Thank you! :+1:

**Pull request merged**
