### PR TITLE
Created Yaml.rb

### PR DESCRIPTION
**Pull request by mvdwoord**
Created a YAML cheatsheet.
This is my first cheatsheet as well as my first pull request on Github so I hope I did everything ok, and that you like it. Please let me know if I misunderstood the rules regarding names with regard to indexing. I'll gladly refactor.

enjoy!
and thanks for making Dash!

### CODE REVIEW

**Comment by Kapeli** [comment]
Added comments in-line. Good job! :+1:

**Comment by mvdwoord** [comment]
I have done all changes based on your comments, hope this looks better.

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by mvdwoord** [comment]
My pleasure. 😀

**Pull request merged**
