### PR TITLE
Master

### PR DESCRIPTION
**Pull request by qinyuhang**
update from css-strike and add iPad Pro resolution

### CODE REVIEW

**Comment by qinyuhang** [comment]
the CSS_Device_Media_Queries is not up to date, so I update it form css-strike and also add iPad Pro resolution. Please add this to the main repo.

**Comment by Kapeli** [comment]
```
line 529: syntax error, unexpected end-of-input, expecting keyword_end
```

**Comment by qinyuhang** [comment]
Hi, I fix that issue of syntax error. And I compiled it locally, it passed the compiling and looks well.

**Comment by Kapeli** [comment]
Thank you! :+1:

**Pull request merged**
