### PR TITLE
Add Cursive cheatsheet

### PR DESCRIPTION
**Pull request by chriskilding**
Add a cheat sheet for the Cursive IDE keyboard shortcuts.

To do:

- [x] Add macOS keybindings
- [ ] Add PC keybindings
- [ ] Add Emacs keybindings

### CODE REVIEW

**Comment by chriskilding** [comment]
I’ve marked this as draft because I ran up against a couple of issues that are worth looking into:

- The CSS styling of `command` mangled non-ASCII character formatting (eg for Shift-Cmd-J the Unicode characters for the Cmd and Shift keys appeared much smaller than the letter J). Therefore I had to use `td_notes` instead, which renders all characters at a sensible line height, but doesn’t style them as nice keyboard keys.
- The `category` supports multiple columns, but not a named header row to disambiguate them. Ideally I’d like to indicate that one column of keybindings is macOS, the next is PC, the next is Emacs, but I can’t do that at the moment.

**Comment by Kapeli** [comment]
1. You should not use ASCII symbols for the keys, so that they are searchable. Use CMD, CTRL, ALT, SHIFT. See #3 at https://github.com/Kapeli/cheatsheets#guidelines

2. `header` and `td_command` might be appropriate. See https://github.com/Kapeli/cheatsheets/blob/006e3a4cbb33c40752cf693b9dbce0181bfcad73/cheatsheets/ASCII_Tables.rb for an example.

**Comment by chriskilding** [comment]
1. That sounds reasonable, I’ll make the adjustments. As an enhancement, It would be cool if cheatset could generate the corresponding symbol for the key as ‘decoration’ whenever it spots CMD, CTRL, SHIFT etc. (So that the symbol does not interfere with searchability, but it’s still shown to make the keybindings easier to read. In particular, keybindings with multiple modifiers would be much easier to read if they were presented as picture + text.
2. Sweet, I didn’t know about the header field.

**Comment by Kapeli** [comment]
Closing due to inactivity.

**Pull request closed without merging**
