### PR TITLE
New Cheatsheet Vim Keys

### PR DESCRIPTION
**Pull request by fskirschbaum**
Based on Vim Cheatsheet from http://vim.rtorr.com/

### CODE REVIEW

**Comment by Kapeli** [comment]
There's already a Vim cheat sheet. Any reason why a new cheat sheet for this is needed instead of expanding the old one?

**Comment by fskirschbaum** [comment]
I made this more for myself than anything. I've used vim.rtorr.com for a while as a reference and decided to integrate into my Dash instead of leaving a window open when I'm SSH'd into a box.

This cheatsheet focuses almost exclusively keyboard shortcuts and avoids a lot of the extra commands. 

In my opinion it's a better 'cheatsheet' than the current, but I actually tend to search between the two as I need to. 

Having made it, I figured I'd open a PR in case anyone else might find it useful as well!

**Comment by Kapeli** [comment]
I'm going to not merge this. Personally I'd much rather have the existing cheat sheet improved or even replaced instead of having 2 cheat sheets. Maybe add the keyboard shortcuts at the top of the old cheat sheet or merge the 2 cheat sheets somehow?

I don't use Vim so I have no idea. I'll leave this issue open. If anyone has any feedback, please comment.

**Comment by fskirschbaum** [comment]
Fair enough. If I get a little more time, I'll look at the other sheet and see if there's a logical way to put integrate them. 

Thanks!

**Pull request closed without merging**
