### PR TITLE
Add Chromium Command Line Switches

### PR DESCRIPTION
**Pull request by charles8xu**
Generate from blog http://peter.sh/experiments/chromium-command-line-switches/

### CODE REVIEW

**Comment by Kapeli** [comment]
Some of the command line options are very large, so the layout looks weird.

screen shot 2017-03-18 at 11 43 55

Try to top using `command` and `td_notes` and use `name` and `notes` instead.

**Comment by charles8xu** [comment]
How about this?
image
image

**Comment by Kapeli** [comment]
Better. Try to use backticks to make these code blocks where appropriate. Eg change "--/prefetch:1" into `--/prefetch:1`

**Comment by charles8xu** [comment]
Did you mean this?
image

**Comment by Kapeli** [comment]
Yep. Also make code blocks in the notes themselves, wherever `--/prefetch:#` is mentioned.

I'd also recommend removing the code block for "The constant OS_WIN must be defined." and changing the name code block into a full-width one (i.e. use three backticks).

Something like this:

```
--/prefetch:1
```

The constant OS_WIN must be defined.

`/prefetch:#` arguments to use when launching various process types. It has been observed that when file reads are consistent for 3 process launches with the same `/prefetch:#` argument, the Windows prefetcher starts issuing reads in batch at process launch. Because reads depend on the process type, the prefetcher wouldn't be able to observe consistent reads if no `/prefetch:#` arguments were used. Note that the browser process has no `/prefetch:#` argument; as such all other processes must have one in order to avoid polluting its profile. Note: # must always be in [1, 8]; otherwise it is ignored by the Windows prefetcher.

**Pull request closed without merging**
