### PR TITLE
Add cheatsheet for Sourcetree

### PR DESCRIPTION
**Pull request by bgannin**
Add a cheatsheet for Atlassian's source code management client, [Sourcetree](https://www.sourcetreeapp.com), on macOS. Matches the latest release (2.7).

### CODE REVIEW

**Comment by bgannin** [comment]
Apologies for the churn. All good now 👍

**Comment by Kapeli** [comment]
Great job. Thank you! 👍

**Comment by Kapeli** [comment]
I've noticed some of the entries don't have key commands. I assume that's intentional.

The cheat sheet is now available in Dash and also at https://kapeli.com/cheat_sheets/Sourcetree.docset/Contents/Resources/Documents/index.

**Comment by bgannin** [comment]
Correct, some commands don't have shortcuts but I wanted to document their purpose within the the category/topic.

**Pull request merged**
