### PR TITLE
Update Gitmoji cheatsheet.

### PR DESCRIPTION
**Pull request by mathieutu**
I've updated the cheatsheet with the exact data from the gitmoji project.
There are some additions, deletions and updates, so I've just took the json and transformed it to the cheatsheet format.

To simplify this process, and the future updates, I've made the choice to remove the categories, and keep the original order. With that, we can totally automatize the update process.

Thanks for the work!

### CODE REVIEW

**Comment by Kapeli** [comment]
Names should not end with a dot (`.`).

@thibmaek any thoughts on not having categories anymore?

**Comment by thibmaek** [comment]
Thanks for getting me in the loop! I've stopped using Dash so I don't really have a true opinion on this, but I'd say I think not categorizing is probably the best way to go indeed. Makes it easier to automate.

**Comment by mathieutu** [comment]
@Kapeli Hi, 
As I said, I've just transformed directly the json to the cheatsheet format, so the dots came from Gitmoji. I eventually can remove them manually, but I think  we should let them, still for simpler updates (we don't touch at the content, just the display)

**Comment by mathieutu** [comment]
Yeah, as I said we could, but I don't recommend it.
I'll make the update.

**Comment by mathieutu** [comment]
Done.

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
