### PR TITLE
Add all PGSQL commands from official docs

### PR DESCRIPTION
**Pull request by rex**
This time, with the backtick issue fixed and a proper working build.

### CODE REVIEW

**Comment by rex** [comment]
Fixed the issues in PR #186, stupid back ticks instead of single quotes. Sorry about that, @Kapeli!

**Comment by Kapeli** [comment]
I'm not sure I like this more than the old cheat sheet. The old cheat sheet is focused on the most popular tasks and also the tasks seem to have a logical order.

Will wait for feedback from other users.

**Comment by rex** [comment]
@Kapeli If it will make it more "merge-able", I will gladly spend a little more time grouping items logically to make it a little more human focused. My reasons for this PR are twofold:

1) There are *a lot* of PGSQL commands and very, very few of them were in the preexisting cheatsheet. 
2) Even if it makes it slightly less human focused, having the exact words used in the documentation can be a tremendous help. 

All the text, wording, etc in this PR is pulled straight from the official PGSQL documentation and no attempt was made on my part to abridge or otherwise reword the text. 

Again, if it will make it more merge-able then I'll gladly spend some time making it more logically grouped and pleasant to use. But I *do strongly* feel that having the complete list of commands in the cheat sheet adds considerable value for the end user (myself among them, using PGSQL very often at work).

**Comment by Kapeli** [comment]
Grouping things logically and ordering them by most used would definitely make me merge it.

**Comment by rex** [comment]
Alright, it's a plan. I'll have that done by tomorrow EOD if things go to plan.

**Comment by Kapeli** [comment]
Is this ready to merge?

**Comment by rex** [comment]
@Kapeli I have a bunch of work locally that I will have cleaned up and pushed up by later today. Sorry for the delay on this.

**Pull request closed without merging**
