### PR TITLE
Add device screen size and Logical resolution

### PR DESCRIPTION
**Pull request by eliyar917**

### CODE REVIEW

**Comment by Kapeli** [comment]
I don't see much use for the logical resolution... I'll wait for feedback from other users to see if this should be added.

The size additions are useful, but they should be under the Displays category, not Resolutions. If you want please make a separate pull request for that.

**Comment by eliyar917** [comment]
As an iOS developer, I often needs to deal with the logical resolution. So, maybe it is useful for some users.

**Comment by dwlt** [comment]
:+1:  for having logical resolutions on the cheat sheet.

**Comment by stevemoser** [comment]
:+1:  I use 'logical' or point resolution more than pixels. I only use pixels for creating assets. Layout all happens in points.

**Comment by eliyar917** [comment]
Should I resubmit pull request?

**Comment by Kapeli** [comment]
Sure, resubmit. I'll close this one.

**Pull request closed without merging**
