### PR TITLE
Add Things cheat sheet

### PR DESCRIPTION
**Pull request by osteele**
Adapted from https://support.culturedcode.com/customer/en/portal/articles/2785159

### CODE REVIEW

**Comment by Kapeli** [comment]
Please follow the guidelines for naming and keyboard shortcuts: https://github.com/Kapeli/cheatsheets#guidelines. Also don't use symbols for the keyboard shortcuts, as they're hard to search for.

**Comment by osteele** [comment]
- [x] Please follow the guidelines for naming and keyboard shortcuts: https://github.com/Kapeli/cheatsheets#guidelines
  - [x] "Keyboard modifiers should be listed in this order: `CMD+CTRL+ALT+SHIFT`"
- [x] Also don't use symbols for the keyboard shortcuts, as they're hard to search for.

---

"Try not to include really common keyboard shortcuts (e.g. Copy, Paste, Undo, Select All)."

This cheatsheet does include one Copy and two Paste commands with the standard shortcut:

| Category | Command | Name |
| -- | -- | -- |
| Create new items | CTRL+C | Paste plain text to create new to-dos |
| Edit items | CTRL+C | Copy a to-do or project |
| Edit items | CTRL+V | Paste a to-do or project |

IMO at least the inclusion of “Paste plain text to create new to-dos" is justified, because pasting to create an item, when there is no editable text area and no text insertion point, is not a standard behavior.

This seems consistent with the inclusion of "Copy line (empty selection)" and "Cut line (empty selection)" in the existing Visual Studio Code cheatsheat: these VS Code commands extend the standard shortcut with nonstandard behavior, and are listed in the current VS Code cheatsheet. This Things shortcut seems like those.

I kept "Edit items" Copy and Paste, in order to have a place to note that these work on both to-do items and projects (which wasn't obvious to me as a user), but this is more debatable.

Let me know if you want me to remove the last two of these, or all of them.

**Comment by Kapeli** [comment]
> This cheatsheet does include one Copy and two Paste commands with the standard shortcut:

They're ok to be included. As long as it's not just "Copy" or "Paste" I'm ok with it.

**Comment by osteele** [comment]
I just committed a changed to downcast "autofill". I now believe everything complies with "Try to use Title Case only for categories."

There are still names that include uppercase words in non-initial position, but I believe these are all proper names within Thing's domain, that the Things documentation capitalizes thus; for example "Quick Entry" and "Today".

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
